In [ ]:
import numpy as np

In [ ]:
np.linspace(0,30,20) #массив интервалов  старт ,стоп,чистота
#часто используется в фостроении графиков по оси X

In [5]:
import numpy as np # Создание массива от 0 до 20 в 4 строки и 5 колонок
my_array=np.arange(0,20).reshape(4,5)   #reshape(-1,1) - изменение формы в 1 столбец 
print(my_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
import numpy as np      # Создание двумерного массива от 0 до 20 в 2 строки и 5 колонок
my_array=np.arange(0,20).reshape(2,2,5)
print(my_array)

In [ ]:
import numpy as np
# Генерация двумерного массива 3x4 из случайных чисел из стандартного нормального распределения
random_matrix = np.random.randn(3, 4)
print(random_matrix)

In [ ]:
x = np.arange(-8, 2, 0.1) # Создание массива с шагом в 0.1
print(x)

## Атрибуты

In [ ]:
my_array.size #Количество Элементов

In [ ]:
my_array.shape #Количество Элементов в каждом измерении

In [ ]:
my_array.ndim #Количество измерений

In [ ]:
my_array.dtype  #Тип данных

In [ ]:
my_array.dtype=np.int8

In [ ]:
my_array.dtype

In [ ]:
my_array.nbytes #Объем памяти ( в байтах)

## Функции

In [ ]:
np.mat([1,2,3,4])

In [ ]:
np.diag([1,2,3,4,5]) # задаем диагональ матрицы

In [ ]:
np.eye(5) # задаем матрицу 5 на 5 по диагонали 1

In [ ]:
np.ones(25).reshape(5,5)

In [ ]:
np.zeros(5)

In [ ]:
np.full([3,2,2,],5) #Создание массива 3х2х2 со всеми 5ми

In [ ]:
np.arange(5,15,0.5) #массив от 5 до 15 с шагом 2

## Слайcинг и индексация

In [ ]:
my_array[2]   #Слайсинг,доступ к строке 2.

In [ ]:
my_array[2,1]  #доступ к строке 2 элемент 1

In [ ]:
my_array[:,3]  #доступ к столбцу 3 и для всех строк

In [ ]:
my_array[0:2, -3:] #доступ к строке 0 1 и столбцу последним трем

## Изменение значений в массиве

In [ ]:
my_array[0,0]=200 # заменяем 0 элемент строки и 0 лем столбца то-есть первый в массиве
my_array

In [ ]:
my_array[1:,:3]=0  # Зануление элементов со2й строки и по 3й столбец
my_array

## Поэлементные операции

In [ ]:
my_array1=np.arange(25,50).reshape(5,5)
my_array1

In [ ]:
result=my_array*my_array1
result

## Методы массива

In [ ]:
import numpy as np
data=np.arange(9).reshape(3,3)
data

In [ ]:
data.max()

In [ ]:
data.min()

In [ ]:
data.sum()

In [ ]:
data.mean()

In [ ]:
data.std() #стандартное оклонение

In [ ]:
data.sum(axis=1) #сумма каждой строки

In [ ]:
data.sum(axis=0) #сумма каждого столбца

In [ ]:
data.T # Транспонирование

In [ ]:
data1=np.arange(9,18).reshape(3,3)
data1

In [ ]:
data.dot(data1) #Скаларное произведение

In [ ]:
data1.diagonal()

In [ ]:
data.resize(9,1)
data

In [ ]:
data2=data.copy()
data2.resize(9,1) #меняем представление массива
data2

## Определитель,Ранг матрицы,Норма,Singular Value Decomposition(SVD),Инверсия

In [ ]:
import numpy as np
mat=np.array([[1,2,3],[4,5,6],[3,6,9]])
mat

In [ ]:
print('Определить матрицы =', int(np.linalg.det(mat)))

In [ ]:
print('Ранг Матрицы =', np.linalg.matrix_rank(mat))

In [ ]:
print('Норма матрицы =', np.linalg.norm(mat))

In [ ]:
print('Singular Value Decomposition(SVD) =', np.linalg.svd(mat))

In [ ]:
print('Инверсия матрицы =', np.linalg.inv(mat))

## Тензоры. ML. Нейронки

In [ ]:
import numpy as np
# Создаем трехмерный тензор размером 3x3x3
tensor = np.random.random((3, 3, 3))
print(tensor)

In [ ]:
import numpy as np

# Создаем тензор размером 3x3x3
tensor1 = np.random.random((3, 3, 3))
tensor2 = np.random.random((3, 3, 3))

# Арифметические операции
sum_tensor = tensor1 + tensor2
diff_tensor = tensor1 - tensor2
product_tensor = tensor1 * tensor2
quotient_tensor = tensor1 / tensor2

# Изменение формы
reshaped_tensor = tensor1.reshape(9, 3)

# Агрегация данных
total_sum = tensor1.sum()
mean_value = tensor1.mean()
max_value = tensor1.max()
min_value = tensor1.min()

# Транспонирование
transposed_tensor = tensor1.transpose(1, 0, 2)

# Матричное умножение
tensor3 = np.random.random((3, 4, 5))
tensor4 = np.random.random((3, 5, 4))
dot_product = np.dot(tensor3, tensor4)
matmul_product = np.matmul(tensor3, tensor4)

# Индексация и срезы
element = tensor1[0, 1, 2]
slice_tensor = tensor1[1, :, :]

# Вывод результатов
print("Sum:\n", sum_tensor)
print("Difference:\n", diff_tensor)
print("Product:\n", product_tensor)
print("Quotient:\n", quotient_tensor)
print("Reshaped tensor shape:", reshaped_tensor.shape)
print("Total sum:", total_sum)
print("Mean value:", mean_value)
print("Max value:", max_value)
print("Min value:", min_value)
print("Transposed tensor shape:", transposed_tensor.shape)
print("Dot product shape:", dot_product.shape)
print("Matmul product shape:", matmul_product.shape)
print("Element at [0, 1, 2]:", element)
print("Slice along first axis:\n", slice_tensor)

In [ ]:
import numpy as np               #Нормализация данных

# Создаем случайные данные
data = np.random.random((100, 3)) * 100
# Нормализуем данные к диапазону [0, 1]
normalized_data = (data - data.min(axis=0)) / (data.max(axis=0) - data.min(axis=0))
print(normalized_data[:5])

In [ ]:
def sigmoid(x):                    #Функции активации Сигмоида
    return 1 / (1 + np.exp(-x))

# Пример использования
input_data = np.array([1.0, 2.0, -1.0])
output_data = sigmoid(input_data)
print(output_data)

In [ ]:
def relu(x):               #Функции активации Relu
    return np.maximum(0, x)

# Пример использования
output_data = relu(input_data)
print(output_data)